<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('settings')->truncate();

        $now = Carbon::now();
        $currentYear = $now->year;
        $nextYear = $currentYear + 1;

        $settings = [
            // School Information
            [
                'key' => 'school_name',
                'display_name' => 'School Name',
                'value' => 'Kenya Model Secondary School',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Full name of the school',
                'is_public' => true,
                'sort_order' => 1,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_short_name',
                'display_name' => 'School Short Name',
                'value' => 'KMSS',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Short name or abbreviation of the school',
                'is_public' => true,
                'sort_order' => 2,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_address',
                'display_name' => 'School Address',
                'value' => 'P.O. Box 12345-00100, Nairobi, Kenya',
                'type' => 'textarea',
                'group' => 'school',
                'description' => 'Official school address',
                'is_public' => true,
                'sort_order' => 3,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_phone',
                'display_name' => 'Phone Number',
                'value' => '+254 712 345 678',
                'type' => 'text',
                'group' => 'school',
                'description' => 'School contact phone number',
                'is_public' => true,
                'sort_order' => 4,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_alternative_phone',
                'display_name' => 'Alternative Phone Number',
                'value' => '+254 723 456 789',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Alternative school contact phone number',
                'is_public' => true,
                'sort_order' => 5,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_email',
                'display_name' => 'Email Address',
                'value' => 'info@kmss.edu.ke',
                'type' => 'email',
                'group' => 'school',
                'description' => 'School email address',
                'is_public' => true,
                'sort_order' => 6,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_website',
                'display_name' => 'School Website',
                'value' => 'www.kmss.edu.ke',
                'type' => 'text',
                'group' => 'school',
                'description' => 'School website URL',
                'is_public' => true,
                'sort_order' => 7,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_logo',
                'display_name' => 'School Logo',
                'value' => 'images/logo.png',
                'type' => 'file',
                'group' => 'school',
                'description' => 'School logo image',
                'is_public' => true,
                'sort_order' => 8,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_motto',
                'display_name' => 'School Motto',
                'value' => 'Strive for Excellence',
                'type' => 'text',
                'group' => 'school',
                'description' => 'School motto',
                'is_public' => true,
                'sort_order' => 9,
                'options' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_type',
                'display_name' => 'School Type',
                'value' => 'Mixed',
                'type' => 'select',
                'options' => json_encode(['Mixed', 'Boys', 'Girls']),
                'group' => 'school',
                'description' => 'Type of school (Mixed, Boys, or Girls)',
                'is_public' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_category',
                'display_name' => 'School Category',
                'value' => 'Boarding and Day',
                'type' => 'select',
                'options' => json_encode(['Boarding', 'Day', 'Boarding and Day']),
                'group' => 'school',
                'description' => 'Category of school (Boarding, Day, or Both)',
                'is_public' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_level',
                'display_name' => 'School Level',
                'value' => 'Secondary',
                'type' => 'select',
                'options' => json_encode(['Pre-primary', 'Primary', 'Secondary', 'Tertiary']),
                'group' => 'school',
                'description' => 'Level of education offered',
                'is_public' => true,
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_county',
                'display_name' => 'County',
                'value' => 'Nairobi',
                'type' => 'text',
                'group' => 'school',
                'description' => 'County where the school is located',
                'is_public' => true,
                'sort_order' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_sub_county',
                'display_name' => 'Sub-County',
                'value' => 'Westlands',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Sub-county where the school is located',
                'is_public' => true,
                'sort_order' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_registration_number',
                'display_name' => 'Registration Number',
                'value' => 'KS/2023/12345',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Official school registration number',
                'is_public' => true,
                'sort_order' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_tsc_code',
                'display_name' => 'TSC Code',
                'value' => 'TSC/2023/6789',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Teachers Service Commission code',
                'is_public' => true,
                'sort_order' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_knec_code',
                'display_name' => 'KNEC Code',
                'value' => '12345678',
                'type' => 'text',
                'group' => 'school',
                'description' => 'Kenya National Examinations Council center code',
                'is_public' => true,
                'sort_order' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Academic Settings
            [
                'key' => 'current_academic_year',
                'display_name' => 'Current Academic Year',
                'value' => "$currentYear-$nextYear",
                'type' => 'text',
                'group' => 'academic',
                'description' => 'The current academic year',
                'is_public' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'current_term',
                'display_name' => 'Current Term',
                'value' => 'Term 1',
                'type' => 'select',
                'options' => json_encode(['Term 1', 'Term 2', 'Term 3']),
                'group' => 'academic',
                'description' => 'The current school term',
                'is_public' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'term_start_date',
                'display_name' => 'Term Start Date',
                'value' => $now->startOfMonth()->format('Y-m-d'),
                'type' => 'date',
                'group' => 'academic',
                'description' => 'Date when the current term started',
                'is_public' => true,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'term_end_date',
                'display_name' => 'Term End Date',
                'value' => $now->addMonths(3)->endOfMonth()->format('Y-m-d'),
                'type' => 'date',
                'group' => 'academic',
                'description' => 'Date when the current term ends',
                'is_public' => true,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'min_promotion_marks',
                'display_name' => 'Minimum Promotion Marks (%)',
                'value' => '40',
                'type' => 'number',
                'group' => 'academic',
                'description' => 'Minimum percentage required for promotion to next class',
                'is_public' => false,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'min_promotion_grade',
                'display_name' => 'Minimum Promotion Grade',
                'value' => 'D',
                'type' => 'text',
                'group' => 'academic',
                'description' => 'Minimum grade required for promotion to next class',
                'is_public' => false,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'publish_results',
                'display_name' => 'Publish Exam Results',
                'value' => '0',
                'type' => 'boolean',
                'group' => 'academic',
                'description' => 'Whether exam results are published and visible to students and parents',
                'is_public' => false,
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'attendance_threshold',
                'display_name' => 'Attendance Threshold (%)',
                'value' => '80',
                'type' => 'number',
                'group' => 'academic',
                'description' => 'Minimum attendance percentage required',
                'is_public' => true,
                'sort_order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'mark_submission_deadline',
                'display_name' => 'Mark Submission Deadline (Days)',
                'value' => '7',
                'type' => 'number',
                'group' => 'academic',
                'description' => 'Number of days after exam when teachers must submit marks',
                'is_public' => false,
                'sort_order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'academic_scheme',
                'display_name' => 'Academic Scheme',
                'value' => '8-4-4',
                'type' => 'select',
                'options' => json_encode(['8-4-4', 'CBC (2-6-3-3-3)', 'Other']),
                'group' => 'academic',
                'description' => 'Educational system the school follows',
                'is_public' => true,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_calendar',
                'display_name' => 'School Calendar Type',
                'value' => 'National',
                'type' => 'select',
                'options' => json_encode(['National', 'International', 'Custom']),
                'group' => 'academic',
                'description' => 'Type of academic calendar followed',
                'is_public' => true,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Boarding Settings
            [
                'key' => 'has_boarding',
                'display_name' => 'Has Boarding Facilities',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'boarding',
                'description' => 'Whether the school has boarding facilities',
                'is_public' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'boarding_fee_per_term',
                'display_name' => 'Boarding Fee Per Term',
                'value' => '35000',
                'type' => 'number',
                'group' => 'boarding',
                'description' => 'Standard boarding fee per term in KES',
                'is_public' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'boarding_capacity',
                'display_name' => 'Boarding Capacity',
                'value' => '500',
                'type' => 'number',
                'group' => 'boarding',
                'description' => 'Total boarding capacity for students',
                'is_public' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'boarding_house_prefect',
                'display_name' => 'Boarding House Prefect Title',
                'value' => 'Boarding Master/Mistress',
                'type' => 'text',
                'group' => 'boarding',
                'description' => 'Title of the boarding house supervisor',
                'is_public' => true,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'boarding_check_in_time',
                'display_name' => 'Boarding Check-In Time',
                'value' => '14:00',
                'type' => 'text',
                'group' => 'boarding',
                'description' => 'Standard check-in time for boarding students',
                'is_public' => true,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'boarding_items_required',
                'display_name' => 'Required Boarding Items',
                'value' => 'Mattress, Bedsheets, Blanket, Toiletries, Personal items',
                'type' => 'textarea',
                'group' => 'boarding',
                'description' => 'List of items boarders are required to bring',
                'is_public' => true,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // System Settings
            [
                'key' => 'currency',
                'display_name' => 'Currency',
                'value' => 'KES',
                'type' => 'text',
                'group' => 'system',
                'description' => 'Currency code',
                'is_public' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'currency_symbol',
                'display_name' => 'Currency Symbol',
                'value' => 'KSh',
                'type' => 'text',
                'group' => 'system',
                'description' => 'Currency symbol',
                'is_public' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'timezone',
                'display_name' => 'Timezone',
                'value' => 'Africa/Nairobi',
                'type' => 'text',
                'group' => 'system',
                'description' => 'System timezone',
                'is_public' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'date_format',
                'display_name' => 'Date Format',
                'value' => 'd/m/Y',
                'type' => 'select',
                'options' => json_encode(['d/m/Y', 'Y-m-d', 'm/d/Y']),
                'group' => 'system',
                'description' => 'Default date format',
                'is_public' => false,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'session_lifetime',
                'display_name' => 'Session Lifetime (Minutes)',
                'value' => '120',
                'type' => 'number',
                'group' => 'system',
                'description' => 'User session timeout in minutes',
                'is_public' => false,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'system_theme',
                'display_name' => 'System Theme',
                'value' => 'default',
                'type' => 'select',
                'options' => json_encode(['default', 'dark', 'light']),
                'group' => 'system',
                'description' => 'Default system theme',
                'is_public' => false,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Finance Settings
            [
                'key' => 'fee_due_days',
                'display_name' => 'Fee Due Days',
                'value' => '30',
                'type' => 'number',
                'group' => 'finance',
                'description' => 'Days after term starts when fees are due',
                'is_public' => true,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'late_payment_penalty',
                'display_name' => 'Late Payment Penalty (%)',
                'value' => '5',
                'type' => 'number',
                'group' => 'finance',
                'description' => 'Percentage penalty for late fee payments',
                'is_public' => true,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'fee_reminder_days',
                'display_name' => 'Fee Reminder Days',
                'value' => '7',
                'type' => 'number',
                'group' => 'finance',
                'description' => 'Days before fee due date to send reminders',
                'is_public' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'mpesa_enabled',
                'display_name' => 'Enable M-PESA Payments',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'finance',
                'description' => 'Whether to enable M-PESA payments',
                'is_public' => true,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'mpesa_shortcode',
                'display_name' => 'M-PESA Paybill/Till Number',
                'value' => '123456',
                'type' => 'text',
                'group' => 'finance',
                'description' => 'M-PESA Paybill or Till Number',
                'is_public' => true,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'bank_account_name',
                'display_name' => 'Bank Account Name',
                'value' => 'Kenya Model Secondary School',
                'type' => 'text',
                'group' => 'finance',
                'description' => 'School bank account name',
                'is_public' => true,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'bank_account_number',
                'display_name' => 'Bank Account Number',
                'value' => '0123456789',
                'type' => 'text',
                'group' => 'finance',
                'description' => 'School bank account number',
                'is_public' => true,
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'bank_name',
                'display_name' => 'Bank Name',
                'value' => 'Kenya Commercial Bank',
                'type' => 'text',
                'group' => 'finance',
                'description' => 'School bank name',
                'is_public' => true,
                'sort_order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'bank_branch',
                'display_name' => 'Bank Branch',
                'value' => 'Nairobi CBD',
                'type' => 'text',
                'group' => 'finance',
                'description' => 'School bank branch',
                'is_public' => true,
                'sort_order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            
            // Communication Settings
            [
                'key' => 'enable_sms',
                'display_name' => 'Enable SMS Notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'communication',
                'description' => 'Enable or disable SMS notifications',
                'is_public' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'enable_email',
                'display_name' => 'Enable Email Notifications',
                'value' => '1',
                'type' => 'boolean',
                'group' => 'communication',
                'description' => 'Enable or disable email notifications',
                'is_public' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'sms_api_key',
                'display_name' => 'SMS API Key',
                'value' => '',
                'type' => 'text',
                'group' => 'communication',
                'description' => 'API key for SMS provider',
                'is_public' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'sms_sender_id',
                'display_name' => 'SMS Sender ID',
                'value' => 'KMSS',
                'type' => 'text',
                'group' => 'communication',
                'description' => 'Sender ID for SMS messages',
                'is_public' => false,
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_facebook',
                'display_name' => 'Facebook Page',
                'value' => 'https://facebook.com/kenyamodelschool',
                'type' => 'text',
                'group' => 'communication',
                'description' => 'School Facebook page URL',
                'is_public' => true,
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_twitter',
                'display_name' => 'Twitter/X Handle',
                'value' => 'https://twitter.com/kenyamodelschool',
                'type' => 'text',
                'group' => 'communication',
                'description' => 'School Twitter/X handle URL',
                'is_public' => true,
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'school_instagram',
                'display_name' => 'Instagram Handle',
                'value' => 'https://instagram.com/kenyamodelschool',
                'type' => 'text',
                'group' => 'communication',
                'description' => 'School Instagram handle URL',
                'is_public' => true,
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('settings')->insert($settings);
    }
}
