<?php

namespace App\Livewire\Timetable;

use App\Models\MyClass;
use App\Models\SchoolTimetable;
use App\Models\Section;
use Illuminate\Support\Collection;
use Livewire\Component;
use Usernotnull\Toast\Concerns\WireToast;

class TimetableRecords extends Component
{
    use WireToast;

    // Main properties
    public $classId;
    public $term;
    public $session;
    
    public $class;
    public Collection $timetableRecords;
    
    // Form control
    public $showModal = false;
    public $isEditingRecord = false;
    public $showDeleteConfirmation = false;
    public $deleteId = null;
    public $timetableRecordForm = [
        'id' => null,
        'name' => '',
        'class_id' => null,
        'section_id' => null,
        'academic_term' => '',
        'academic_session' => '',
        'is_active' => false,
        'description' => '',
        'is_auto_generated' => true,
    ];
    
    public $sections = [];
    
    protected $rules = [
        'timetableRecordForm.name' => 'required|string|max:100',
        'timetableRecordForm.class_id' => 'required|exists:my_classes,id',
        'timetableRecordForm.academic_term' => 'required|string',
        'timetableRecordForm.academic_session' => 'required|string',
        'timetableRecordForm.section_id' => 'nullable|exists:sections,id',
        'timetableRecordForm.description' => 'nullable|string',
    ];

    public function mount($classId, $term, $session)
    {
        $this->classId = $classId;
        $this->term = $term;
        $this->session = $session;
        $this->timetableRecords = new Collection();
        $this->loadData();
    }
    
    public function loadData()
    {
        $this->class = MyClass::find($this->classId);
        
        if (!$this->class) {
            toast()->danger('Class not found')->push();
            return;
        }
        
        $this->sections = Section::where('my_class_id', $this->classId)->get();
        
        $this->timetableRecords = SchoolTimetable::where('class_id', $this->classId)
            ->where('academic_term', $this->term)
            ->where('academic_session', $this->session)
            ->get();
    }
    
    public function createTimetableRecord()
    {
        // Debug info
        toast()->info('Creating timetable record...')->push();
        
        // First check if the class property is set
        if (!$this->class) {
            $this->loadData();
        }
        
        $this->timetableRecordForm = [
            'id' => null,
            'name' => "Timetable for {$this->class->name} ({$this->term}, {$this->session})",
            'class_id' => $this->classId,
            'section_id' => null,
            'academic_term' => $this->term,
            'academic_session' => $this->session,
            'is_active' => false,
            'description' => '',
            'is_auto_generated' => true,
        ];
        
        $this->isEditingRecord = true;
        $this->showModal = true;
    }
    
    public function editTimetableRecord($id)
    {
        $timetable = SchoolTimetable::findOrFail($id);
        
        // Check if the name follows the auto-generated pattern
        $isAutoGenerated = (preg_match('/^Timetable for .+ \(.+, .+\)(\s\(\d+\))?$/', $timetable->name) === 1);
        
        $this->timetableRecordForm = [
            'id' => $timetable->id,
            'name' => $timetable->name,
            'class_id' => $timetable->class_id,
            'section_id' => $timetable->section_id,
            'academic_term' => $timetable->academic_term,
            'academic_session' => $timetable->academic_session,
            'is_active' => $timetable->is_active,
            'description' => $timetable->description,
            'is_auto_generated' => $isAutoGenerated,
        ];
        
        $this->isEditingRecord = true;
        $this->showModal = true;
    }
    
    public function saveTimetableRecord()
    {
        $this->validate();
        
        try {
            // Check if the name already exists for a different record and make it unique if needed
            $name = $this->timetableRecordForm['name'];
            $className = $this->class ? $this->class->name : '';
            
            // Only use generateUniqueName for new records or if this is still auto-generated
            if (!$this->timetableRecordForm['id'] || 
                ($this->timetableRecordForm['is_auto_generated'] ?? false)) {
                $name = SchoolTimetable::generateUniqueName(
                    $className,
                    $this->timetableRecordForm['academic_term'],
                    $this->timetableRecordForm['academic_session'],
                    $name // Pass current name as custom name
                );
            }
            
            $data = [
                'name' => $name,
                'class_id' => $this->timetableRecordForm['class_id'],
                'section_id' => $this->timetableRecordForm['section_id'],
                'academic_term' => $this->timetableRecordForm['academic_term'],
                'academic_session' => $this->timetableRecordForm['academic_session'],
                'is_active' => $this->timetableRecordForm['is_active'],
                'description' => $this->timetableRecordForm['description'],
            ];
            
            if ($this->timetableRecordForm['id']) {
                $timetable = SchoolTimetable::findOrFail($this->timetableRecordForm['id']);
                $timetable->update($data);
                
                toast()->success('Timetable record updated successfully')->push();
            } else {
                $timetable = SchoolTimetable::create($data);
                
                // If set as active, deactivate others
                if ($timetable->is_active) {
                    SchoolTimetable::where('id', '!=', $timetable->id)
                        ->where('class_id', $timetable->class_id)
                        ->where('academic_term', $timetable->academic_term)
                        ->where('academic_session', $timetable->academic_session)
                        ->update(['is_active' => false]);
                }
                
                toast()->success('Timetable record created successfully')->push();
                
                // If name was changed to ensure uniqueness, notify the user
                if ($name !== $this->timetableRecordForm['name']) {
                    toast()->info("Name was changed to ensure uniqueness: $name")->push();
                }
            }
            
            $this->closeModal();
            $this->loadData();
            
        } catch (\Exception $e) {
            toast()->danger('Error: ' . $e->getMessage())->push();
        }
    }
    
    public function confirmDeleteTimetableRecord($id)
    {
        // Setup confirmation dialog
        $this->deleteId = $id;
        $this->showDeleteConfirmation = true;
    }
    
    public function deleteTimetableRecord()
    {
        try {
            if (!$this->deleteId) {
                toast()->warning('No timetable record selected for deletion')->push();
                return;
            }
            
            SchoolTimetable::findOrFail($this->deleteId)->delete();
            toast()->success('Timetable record deleted successfully')->push();
            
            // Reset confirmation state
            $this->showDeleteConfirmation = false;
            $this->deleteId = null;
            
            $this->loadData();
            
        } catch (\Exception $e) {
            toast()->danger('Error: ' . $e->getMessage())->push();
        }
    }
    
    public function toggleActiveTimetable($id)
    {
        try {
            $timetable = SchoolTimetable::findOrFail($id);
            
            // If already active and trying to deactivate
            if ($timetable->is_active) {
                $timetable->update(['is_active' => false]);
                toast()->info('Timetable deactivated')->push();
            } else {
                // Deactivate all others in same class/term/session
                SchoolTimetable::where('class_id', $timetable->class_id)
                    ->where('academic_term', $timetable->academic_term)
                    ->where('academic_session', $timetable->academic_session)
                    ->update(['is_active' => false]);
                    
                // Activate the selected timetable
                $timetable->update(['is_active' => true]);
                toast()->success('Timetable activated successfully')->push();
            }
            
            $this->loadData();
            
        } catch (\Exception $e) {
            toast()->danger('Error: ' . $e->getMessage())->push();
        }
    }
    
    public function cancelDelete()
    {
        $this->showDeleteConfirmation = false;
        $this->deleteId = null;
    }
    
    public function closeModal()
    {
        $this->showModal = false;
        $this->isEditingRecord = false;
        $this->timetableRecordForm = [
            'id' => null,
            'name' => '',
            'class_id' => $this->classId,
            'section_id' => null,
            'academic_term' => $this->term,
            'academic_session' => $this->session,
            'is_active' => false,
            'description' => '',
            'is_auto_generated' => true,
        ];
    }
    
    public function render()
    {
        return view('livewire.timetable.timetable-records');
    }
    
    /**
     * Switch to a different tab in the timetable interface
     */
    public function switchTab($tab)
    {
        $this->dispatch('switchTab', $tab);
    }
} 